server:
  port: 9000

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miidlaj/locus-config-server
          clone-on-start: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.206.125.179:8761/eureka
  instance:
    hostname: 15.206.125.179
